unionlabs/union

- LICENSE-APACHE
- LICENSE-MIT
TODO: Is "Union Labs Inc." the appropriate entity?
> Add dual MIT/Apache2 licenses

- Cargo.lock
- cosmwasm/ucs01-relay-api/src/types.rs
- cosmwasm/ucs01-relay/Cargo.toml
- cosmwasm/ucs01-relay/src/contract.rs
- cosmwasm/ucs01-relay/src/msg.rs
- cosmwasm/ucs01-relay/src/protocol.rs
- cosmwasm/ucs01-relay/src/state.rs
- dictionary.txt
> feat(ucs01): base58 for foreign denom encoding

- dictionary.txt
- site/astro.config.ts
- site/package-lock.json
- site/site.nix
- site/src/components/GraphQL.astro
- site/src/content/docs/docs/integrations/api/graphql.mdx
- site/src/content/docs/docs/integrations/getting-started.mdx
This should be merged by @qlp once we have `v1` live. 
Optionally @o-az we embed the snippets in a playground (added bonus if the queries are checked during compile time)
> docs(graphql): document graphql.union.build

- app/src/lib/components/transfer-details.svelte
- app/src/lib/graphql/fragments/transfers.ts
- app/src/lib/graphql/queries/transfer-details.ts
- app/src/lib/queries/transfers.ts
- app/src/lib/types.ts
- app/src/routes/transfer/(components)/transfer-form.svelte
- fix(app): v1 schema issues
- fix(app): use correct forwards info
> app port fix

- app/src/lib/components/connect/connection.svelte
> fix(app): change text color

- app/src/lib/components/search/cmdk.svelte
> fix(app): restore search

- .github/workflows/pr-cleanup.yml
im tired of the intrusive netlify comment :/
> fix: auto remove netlify comment when no site changes

- Cargo.toml
- dictionary.txt
- lib/beacon-api/src/client.rs
- lib/chain-utils/src/arbitrum.rs
- lib/chain-utils/src/berachain.rs
- lib/chain-utils/src/cosmos.rs
- lib/chain-utils/src/ethereum.rs
- lib/queue-msg/src/lib.rs
- lib/queue-msg/src/optimize.rs
- lib/unionlabs/src/aptos/state_proof.rs
- lib/unionlabs/src/berachain.rs
- lib/unionlabs/src/cosmos/tx/fee.rs
- lib/unionlabs/src/cosmos/tx/sign_doc.rs
- lib/unionlabs/src/cosmos/tx/tx_raw.rs
- lib/unionlabs/src/ethereum/config.rs
- lib/unionlabs/src/lib.rs
- lib/unionlabs/src/macros.rs
- lib/unionlabs/src/traits.rs
- lib/voyager-message/src/call.rs
- lib/voyager-message/src/context.rs
- lib/voyager-message/src/data.rs
- lib/voyager-message/src/lib.rs
- lib/voyager-message/src/module.rs
- lib/voyager-message/src/pass.rs
- lib/voyager-message/src/rpc/server.rs
- light-clients/arbitrum-light-client/src/client.rs
- light-clients/scroll-light-client/src/client.rs
- voyager/devnet-config.json
- voyager/modules/client/cometbls/src/main.rs
- move to `#[model]` for some types in `voyager-message`
- small fix for handling invalid plugin messages as fatal
- improve docs in `voyager-message` and all dependencies
- clean up in `voyager-message`, `chain-utils`, and `unionlabs` (remove a lot of unused code)
> chore: improve docs across the workspace & small fix

- Cargo.lock
- Cargo.toml
- lib/chain-utils/src/cosmos_sdk.rs
- lib/cometbls-groth16-verifier/src/lib.rs
- lib/unionlabs/src/union/ics23/merkle_proof.rs
- networks/devnet.nix
- voyager/devnet-config.json
- voyager/modules/client/cometbls/src/main.rs
- voyager/modules/client/tendermint/Cargo.toml
- voyager/modules/client/tendermint/src/call.rs
- voyager/modules/client/tendermint/src/callback.rs
- voyager/modules/client/tendermint/src/data.rs
- voyager/modules/client/tendermint/src/main.rs
- voyager/modules/consensus/tendermint/Cargo.toml
- voyager/modules/consensus/tendermint/src/call.rs
- voyager/modules/consensus/tendermint/src/callback.rs
- voyager/modules/consensus/tendermint/src/data.rs
- voyager/modules/consensus/tendermint/src/main.rs
- voyager/modules/transaction/cosmos-sdk/src/main.rs
> feat(voyager): tendermint modules

- lib/reconnecting-jsonrpc-ws-client/src/lib.rs
- lib/voyager-core/src/lib.rs
- lib/voyager-message/src/call.rs
- lib/voyager-message/src/context.rs
- lib/voyager-message/src/lib.rs
- lib/voyager-message/src/module.rs
- lib/voyager-message/src/rpc.rs
- lib/voyager-message/src/rpc/server.rs
- voyager/modules/chain/cosmos-sdk/src/main.rs
- voyager/modules/chain/movement/src/main.rs
- voyager/modules/client/cometbls/src/main.rs
- voyager/modules/client/ethereum/src/main.rs
- voyager/modules/client/movement/src/main.rs
- voyager/modules/client/tendermint/src/main.rs
- voyager/modules/consensus/cometbls/src/main.rs
- voyager/modules/consensus/ethereum/src/main.rs
- voyager/modules/consensus/movement/src/main.rs
- voyager/modules/consensus/tendermint/src/main.rs
> feat(voyager): add consensus type

- dictionary.txt
- site/src/assets/images/big-whale.png
- site/src/components/ButtonA.astro
- site/src/components/ContainedSection.astro
- site/src/components/Footer.astro
- site/src/components/Header.astro
- site/src/components/sections/EcosystemSection.astro
- site/src/components/sections/MarqueeSection.astro
- site/src/components/sections/landing/BorderIntro.astro
- site/src/components/sections/landing/ConsensusSection.astro
- site/src/components/sections/landing/ExecutionSection.astro
- site/src/components/sections/landing/ZkSection.astro
- site/src/components/typography/LightedTitle.astro
- site/src/components/typography/h2.astro
- site/src/components/typography/subtitle.astro
- site/src/lib/matrix-cover.ts
- site/src/pages/ecosystem.astro
- site/src/pages/index.astro
- site/src/styles/marquee.css
- feat(site): centered cover composition
- fix(site): cleanup header
- fix(site): alignments
- feat(site): add wait time before camera rotation
- fix(site): unslectable cover card
- fix(site): reduce section height
- fix(app): use video instead of spline
- fix(site): use video for execution section
- fix(site): misc fixes
> site improvements

- site/src/components/ContainedSection.astro
- site/src/components/Footer.astro
- site/src/components/MatrixCover.astro
- site/src/components/sections/landing/BorderIntro.astro
- site/src/components/sections/landing/ConsensusSection.astro
- site/src/components/sections/landing/ExecutionSection.astro
- site/src/components/sections/landing/IntroSection.astro
- site/src/components/sections/landing/ZkSection.astro
- site/src/components/typography/QuoteSubTitle.astro
- site/src/layouts/SectionsLayout.astro
- site/src/lib/matrix-cover.ts
- fix(site): wave adjustments
- fix(site): improve radial glass quality
- fix(site): section cleanups
- fix(site): layout fixes, new video links
- fix(site): white flash on slow internet
> Misc site fixes

- evm/contracts/core/02-client/IBCClient.sol
- evm/contracts/core/03-connection/IBCConnection.sol
- evm/contracts/core/04-channel/IBCChannel.sol
- evm/contracts/core/04-channel/IBCPacket.sol
- evm/contracts/core/24-host/IBCStore.sol
- evm/contracts/core/Types.sol
- evm/tests/src/02-client/IBCClient.t.sol
- evm/tests/src/03-connection/IBCConnection.t.sol
- evm/tests/src/04-channel/IBCChannel.t.sol
- evm/tests/src/04-channel/IBCPacket.t.sol
- avoids duplicate
- simpler codegen
- easy to add new errors
> feat(evm): centralize errors

- evm/contracts/apps/Base.sol
- evm/contracts/apps/ucs/00-pingpong/PingPong.sol
- evm/contracts/apps/ucs/01-relay/Relay.sol
- evm/contracts/apps/ucs/02-nft/NFT.sol
- evm/contracts/core/02-client/IBCClient.sol
- evm/contracts/core/02-client/IIBCClient.sol
- evm/contracts/core/03-connection/IBCConnection.sol
- evm/contracts/core/04-channel/IBCChannel.sol
- evm/contracts/core/04-channel/IBCPacket.sol
- evm/contracts/core/05-port/IIBCModule.sol
- evm/contracts/core/24-host/IBCStore.sol
- evm/contracts/core/25-handler/IBCMsgs.sol
- evm/contracts/core/Types.sol
- evm/scripts/Deploy.s.sol
- evm/tests/src/02-client/IBCClient.t.sol
- evm/tests/src/03-connection/IBCConnection.t.sol
- evm/tests/src/04-channel/IBCChannel.t.sol
- evm/tests/src/04-channel/IBCPacket.t.sol
- get rid of counterparty structure and inline for more efficient slots packing
- normalize handshake (no longer ask for the channel in the msg)
- add clientType
- remove deprecated test
> feat(evm): refactor

- evm/contracts/core/04-channel/IBCPacket.sol
- evm/evm.nix
- evm/scripts/Deploy.s.sol
- reintroduce solidity coverage
- upgrade solady/deployer
- optimize commitment key computation
> feat(evm): upgrade and refactor

- dictionary.txt
- flake.nix
- lib/aptos.nix
- move/ibc-api/sources/ibc_api.move
- move/move-ibc/sources/bcs_utils.move
- move/move-ibc/sources/channel_end.move
- move/move-ibc/sources/cometbls_light_client.move
- move/move-ibc/sources/connection_end.move
- move/move-ibc/sources/groth16_verifier.move
- move/move-ibc/sources/height.move
- move/move-ibc/sources/ibc.move
- move/move-ibc/sources/ibc_commitment.move
- move/move-ibc/sources/ics23.move
- move/move-ibc/sources/packet.move
- move/move-ibc/sources/proto_utils.move
- move/move-ibc/tests/channel_test.move
- move/move-ibc/tests/client_test.move
- move/move-ibc/tests/connection_test.move
- move/move-ibc/tests/ibccommitment_test.move
- move/ping-pong/sources/ping_pong.move
- move/ucs01-relay/sources/eth_abi.move
- move/ucs01-relay/sources/relay.move
- move/ucs01-relay/sources/token_denom.move
- treefmt.nix
- Introduced `submit_misbehaviour` entrypoint.
- Added misbehaviour check during `update_client`.
- Added `movefmt` to `nix fmt`.
- Formatted all move files.
> Aptos Move IBC misbehaviours and `movefmt`

- ceremony/src/lib/state/contributor.svelte.ts
As the queue gets bigger and bigger I think it's better to reduce the request a bit
> fix(ceremony): reduce polling

- lib/voyager-message/src/module.rs
- voyager/modules/chain/cosmos-sdk/src/main.rs
- voyager/modules/chain/ethereum/src/main.rs
- voyager/modules/chain/movement/src/main.rs
> chore: remove query_latest_height_as_destination

- evm/contracts/core/24-host/IBCCommitment.sol
- lib/cometbls-groth16-verifier/src/lib.rs
- lib/unionlabs/src/ethereum/slot.rs
- lib/unionlabs/src/ics24.rs
- lib/unionlabs/src/uint.rs
- voyager/modules/chain/ethereum/src/main.rs
- encodePacked is considered deprecated and may be removed in the future
> fix(ics24): non packed abi encoding for commitment paths

- site/src/components/BlinkWhale.astro
- site/src/components/Footer.astro
- site/src/components/Header.astro
- site/src/components/SplineResizing.astro
- site/src/components/sections/MarqueeSection.astro
- site/src/components/sections/landing/ConsensusSection.astro
- site/src/components/sections/landing/ExecutionSection.astro
- site/src/components/sections/landing/ZkSection.astro
- site/src/components/typography/h2.astro
- site/src/pages/ecosystem.astro
- site/src/pages/index.astro
- Header instant close
- Blinking whale
- Faded marquee and made it greyscale
- Adjusted animation sections on `/`
- Added link to ceremony
- Removed some logs
> fix(site): site edits

- site/src/components/ContainedSection.astro
- site/src/components/Header.astro
- site/src/pages/ecosystem.astro
- site/tailwind.config.ts
- **fix(site): ecosystem controls alignment**
- **fix(site): research in header**
- **fix(site): ecosystem grid sizing**
- **fix(site): don't auto open/close the filter list**
> Fix ecosystem layout on mobile

- site/src/lib/matrix-cover.ts
We should not track touch on matrix animation
> fix(site): dont track touch

- site/src/components/sections/DeepDiveSection.astro
- site/src/components/sections/MarqueeSection.astro
- site/src/layouts/AnimationLayout.astro
- site/src/pages/blog/index.astro
- site/src/pages/ecosystem.astro
- site/src/pages/learn.astro
- site/src/pages/team.astro
- Add padding to marquee
- Dont slide text if same page
> fix(site): adjustments

- site/package-lock.json
- site/package.json
- site/site.nix
- site/src/components/DropdownMenu.astro
- site/src/components/Header.astro
- site/src/layouts/BaseLayout.astro
- **fix: site menu not working in blog page**
> fix: site menu in blog page

- dictionary.txt
- networks/mkCosmosDevnet.nix
- **feat(devnet): add cpu profile**
- **feat(devnet): map pprof_laddr**
- **fix(devnet): don't prefix with http**
> cpu profile devnet

- Cargo.lock
- Cargo.toml
- cosmwasm/ucs00-pingpong/src/msg.rs
- cosmwasm/union-ibc/app/ucs00-pingpong/Cargo.toml
- cosmwasm/union-ibc/app/ucs00-pingpong/src/contract.rs
- cosmwasm/union-ibc/app/ucs00-pingpong/src/lib.rs
- cosmwasm/union-ibc/app/ucs00-pingpong/src/msg.rs
- cosmwasm/union-ibc/app/ucs00-pingpong/src/state.rs
- cosmwasm/union-ibc/core/msg/src/module.rs
- cosmwasm/union-ibc/light-clients/ethereum/src/client.rs
- cosmwasm/union-ibc/light-clients/ethereum/types/src/client_state.rs
- cosmwasm/union-ibc/light-clients/ethereum/types/src/consensus_state.rs
- voyager/modules/client/ethereum/src/main.rs
- voyager/modules/consensus/ethereum/src/main.rs
1. Implement ping pong in union ibc
2. Track the latest height instead of the latest slot in ethereum light client
> ping pong in union ibc and ethereum light client fixes

- site/src/components/DropdownMenu.astro
- site/src/components/Header.astro
- site/src/layouts/AnimationLayout.astro
- site/src/lib/contentful/types.ts
- site/src/pages/ecosystem.astro
pr to color categories, use bgColor and textColor in cms, defaults to b/w
> feat(site): add cat cms colors

- lib/voyager-message/src/context.rs
- voyager/config.json
- voyager/src/main.rs
> fix(voyager): add client bootstrap modules to config

- voyager/plugins/transaction/aptos/src/main.rs
- voyager/plugins/transaction/cosmos-sdk/src/main.rs
- voyager/plugins/transaction/ethereum/src/main.rs
- voyager/src/cli.rs
- voyager/src/main.rs
> add update client client voyager

- cosmwasm/ibc-union/README.md
- docs/src/content/docs/protocol/deployments.mdx
- evm/README.md
- **docs(ibc-union): centralize deployment addresses**
- **docs(ibc-union): convert address lists to tables**
> 3424 centralize deployments info

- .vscode/extensions.json
- .vscode/settings.json
extension tries to install a broken LSP
> fix(vscode): remove even-better-toml

- lib/beacon-api-types/src/beacon_block_body.rs
- lib/beacon-api-types/src/lib.rs
- lib/ssz/src/lib.rs
- lib/unionlabs-primitives/src/bytes.rs
- lib/unionlabs-primitives/src/compat.rs
- lib/unionlabs-primitives/src/fixed_bytes.rs
- lib/unionlabs-primitives/src/lib.rs
- lib/unionlabs/src/aptos/account.rs
- lib/unionlabs/src/aptos/state_proof.rs
- lib/unionlabs/src/aptos/transaction_proof.rs
- lib/unionlabs/src/cosmos/crypto/secp256k1.rs
- voyager/modules/client-bootstrap/movement/src/main.rs
> refactor(unionlabs-primitives): rename `Hash` -> `FixedBytes`

- evm/evm.nix
> Expose ucs03 in hubble-abis

- app/app.nix
- app/package-lock.json
- app/package.json
> feat(app): use typescript-sdk v0.0.40

- cosmwasm/ibc-union/light-clients/ethereum/src/errors.rs
- lib/beacon-api-types/Cargo.toml
- lib/beacon-api-types/src/attestation_data.rs
- lib/beacon-api-types/src/beacon_block.rs
- lib/beacon-api-types/src/beacon_block_header.rs
- lib/beacon-api-types/src/fork_parameters.rs
- lib/beacon-api-types/src/lib.rs
- lib/beacon-api-types/src/light_client_finality_update.rs
- lib/beacon-api-types/src/light_client_update.rs
- lib/beacon-api/examples/tests.rs
- lib/beacon-api/src/client.rs
- lib/beacon-api/src/types.rs
- lib/ethereum-light-client-types/src/client_state.rs
- lib/ethereum-light-client-types/src/consensus_state.rs
- lib/ethereum-light-client-types/src/header.rs
- lib/ethereum-light-client-types/src/light_client_update.rs
- lib/ethereum-light-client-types/src/light_client_update_data.rs
- lib/ethereum-sync-protocol/src/error.rs
- lib/ethereum-sync-protocol/src/lib.rs
- lib/ethereum-sync-protocol/src/utils.rs
- voyager/modules/client-bootstrap/ethereum/src/main.rs
- voyager/modules/consensus/ethereum/src/main.rs
- voyager/plugins/client-update/ethereum/src/main.rs
> feat(beacon-api-types): introduce slot newtype

- typescript-sdk/package.json
- typescript-sdk/playground/stargaze-to-holesky.ts
- typescript-sdk/playground/union-to-holesky.ts
- typescript-sdk/src/cosmos/client.ts
- typescript-sdk/src/pfm.ts
- **feat(ts-sdk): configure union-testnet-9**
- **feat(ts-sdk): configure elgafar-1**
- **feat(ts-sdk): transfer from stargaze to holesky**
- **feat(ts-sdk): randomize salt for cosmos transfers**
- **fix(ts-sdk): note that quote_token is hardcoded for now**
- **chore(ts-sdk): publish v0.0.45**
> Initiate UCS03 CosmWasm transfers from TypeScript SDK

- app/src/lib/components/packet-details.svelte
- app/src/lib/components/packet-path.svelte
- app/src/lib/components/transfer-details.svelte
- app/src/lib/components/truncate.svelte
- app/src/lib/graphql/queries/packet-details.ts
- app/src/lib/graphql/queries/transfer-details.ts
- app/src/lib/queries/packets.ts
- app/src/routes/explorer/packets/[chain_id]/[connection_id]/[channel_id]/[sequence]/+page.svelte
- **feat(app): fetch ibc-union packet details**
- **feat(app): improve packet-path styling**
- **feat(app): show basic ibc-union transfer details**
- **feat(app): show traces for ibc-union transfers**
- **feat(app): render transfer details**
- **fix(app): gracefully handle (un)availability of token details**
- **fix(app): address overflow with truncation**
> Fetch transfer details

- app/src/lib/components/TransferFrom/components/Cube/faces/Transfer.svelte
- app/src/lib/components/packet-path.svelte
- app/src/lib/components/transfer-details.svelte
- app/src/lib/components/truncate.svelte
- app/src/lib/stores/submitted-transfers.ts
- **feat(app): show prefilled transfer data**
- **fix(app): incomplete packet path connection/channel styling**
- **feat(app): cleanup confirm screen**
> Prefill transfers and clean up transfer submission flow

- lib/cometbft-rpc/src/lib.rs
- lib/cometbft-rpc/src/rpc_types.rs
- lib/cometbft-types/src/lib.rs
- lib/cometbft-types/src/types/block_id.rs
- lib/cometbft-types/src/types/part_set_header.rs
- lib/voyager-message/src/lib.rs
> fix(cometbft-rpc): fix serde for empty hashes

- cosmwasm/ibc-union/app/ucs03-zkgm/src/com.rs
- cosmwasm/ibc-union/app/ucs03-zkgm/src/contract.rs
- cosmwasm/ibc-union/app/ucs03-zkgm/src/lib.rs
- cosmwasm/ibc-union/app/ucs03-zkgm/src/msg.rs
- partially handle execute/timeout/ack for batch and multiplex packets
- unhandled: non eureka multiplex (require refactoring the execution with submessage handling etc...)
> feat(zgkm): handle batch+multiplex in cosmwasm

- flake.lock
- flake.nix
- networks/devnet.nix
> chore: remove unused flake inputs

- typescript-sdk/package.json
fixes this https://github.com/unionlabs/union/actions/runs/12861875368/job/35855909407#step:5:39
> fix(ts-sdk): check-package script

- voyager/Cargo.toml
> fix(voyager): json for reqwest

- app/src/lib/components/token-quality-level.svelte
- app/src/lib/components/token.svelte
- app/src/lib/components/truncate.svelte
- app/src/lib/queries/balance/index.ts
- app/src/lib/queries/stats.ts
- app/src/lib/queries/tokens.ts
- app/src/lib/types.ts
- **feat(app): fetch onchain asset info**
- **feat(app): show both graphql and onchain token info**
> Show both graphql and onchain data for assets

- typescript-sdk/package.json
- typescript-sdk/playground/arbitrum-to-arbitrum-legacy.ts
- typescript-sdk/playground/arbitrum-to-stride-legacy.ts
- typescript-sdk/playground/arbitrum-to-union-legacy.ts
- typescript-sdk/playground/holesky-to-sepolia.ts
- typescript-sdk/src/evm/client.ts
- **feat(typescript-sdk): approval on the client**
- **fix(typescript-sdk): cleanup playground**
- **chore(typescript-sdk): release v0.0.51**
> TypeScript SDK v0.0.51

- app/src/lib/components/header/header.svelte
- app/src/lib/components/trace.svelte
- app/src/lib/components/transfer-details.svelte
- app/src/lib/components/transfers-table/transfers-table.svelte
- **feat(app): timestamps in transfers list, testnet 9 badge**
- **fix(app): cosmos transaction links**
> graceful transfer tx

- evm/README.md
> docs: update evm/README.md

- app/src/lib/components/TransferFrom/components/Cube/faces/Chains.svelte
- app/src/lib/components/TransferFrom/components/Cube/faces/Transfer.svelte
- app/src/lib/components/TransferFrom/index.svelte
- app/src/lib/components/address.svelte
- app/src/lib/components/header/header.svelte
- app/src/lib/components/stepper.svelte
- app/src/lib/components/tables/packets.svelte
- app/src/lib/components/token.svelte
- app/src/lib/components/transfer-details.svelte
- app/src/lib/graphql/queries/transfer-details.ts
- app/src/lib/stores/highlight.ts
- app/src/lib/stores/submitted-transfers.ts
- app/src/lib/transfer/transfer.ts
- app/src/routes/explorer/(components)/table.svelte
- site/src/components/EmailSignup.astro
- **feat(app): submit cosmos transfers**
- **feat(app): highlight all instances of address**
- **feat(app): improve hovers and truncations**
- **fix(app): sender/receiver justification**
> Submit transfers, highlight identical items, show transfer details before confirmation

- voyager/plugins/client-update/state-lens/src/main.rs
> fix(voyager): use l1 chain id when fetching l1 latest height

- cosmwasm/ibc-union/core/light-client-interface/src/lib.rs
- cosmwasm/ibc-union/core/msg/src/lightclient.rs
- cosmwasm/ibc-union/core/src/contract.rs
- cosmwasm/ibc-union/core/src/tests/channel/ibc_channel.rs
- cosmwasm/ibc-union/core/src/tests/client/ibc.rs
- cosmwasm/ibc-union/core/src/tests/connection/ibc.rs
- cosmwasm/ibc-union/light-clients/arbitrum/src/client.rs
- cosmwasm/ibc-union/light-clients/berachain/src/client.rs
- cosmwasm/ibc-union/light-clients/cometbls/src/client.rs
- cosmwasm/ibc-union/light-clients/ethereum/src/client.rs
- cosmwasm/ibc-union/light-clients/movement/src/client.rs
- cosmwasm/ibc-union/light-clients/state-lens-ics23-mpt/src/client.rs
- cosmwasm/ibc-union/light-clients/tendermint/src/client.rs
Emit `CreateStateLensClient` event in cosmwasm
> chore: emit state lens client event

- app/src/lib/components/balance-fetcher.svelte
- app/src/lib/stores/balances.ts
- app/src/routes/balances/+page.svelte
- app/src/routes/balances/UserBalances.svelte
- **feat(app): fetch evm balances with new fetcher**
- **feat(app): show balances of connected wallet**
- **feat(app): delete balances on disconnect**
- **feat(app): simplify blanace fetching**
- **feat(app): balancefetcher component**
> New balances fetcher in app

- app/src/lib/components/address.svelte
- app/src/lib/components/connect/connect.svelte
- app/src/lib/components/table-cells/cell-assets.svelte
- app/src/lib/components/table-cells/cell-timestamp.svelte
- app/src/lib/components/token.svelte
- app/src/lib/components/transfer-details.svelte
- **fix(app): misc refinements**
- **fix(app): hide aptos wallet**
> UI refinements

- app/src/lib/components/TransferFrom/components/Cube/faces/Assets.svelte
- app/src/lib/components/TransferFrom/components/SelectedAsset.svelte
- app/src/lib/components/connect/connect.svelte
- app/src/lib/components/table-cells/cell-assets.svelte
- app/src/lib/components/token.svelte
- app/src/lib/components/transfer-details.svelte
- app/src/lib/stores/user.ts
If you want to see all token details, select "show token details" in the sidebar.
- **feat(app): toggle token details**
- **feat(app): more refined token displayingj**
> Token UI refinements

- app/app.nix
- app/package-lock.json
- app/package.json
- app/src/lib/stores/balances.ts
- **feat: fetch cw20 balances**
- **chore: checkpoint**
- **feat: cw20 balances**
> fetch cw20 balances

- app/src/lib/components/TransferFrom/components/Cube/faces/Transfer.svelte
- app/src/routes/explorer/(components)/pixel-graph.svelte
- **feat(app): approve CW20 transfers**
- **fix(app): remove toasts**
> Approve CW20 transfers in app

- app/README.md
- app/src/lib/chain-details.svelte
- app/src/lib/components/token-quality-level.svelte
- app/src/lib/components/token.svelte
- app/src/lib/components/transfer-details.svelte
- app/src/lib/stores/tokens.ts
- **feat(app): more refined checkmarks**
- **feat(app): better warning symbols**
> app ui refinements 3

- app/src/lib/components/TransferFrom/components/Cube/faces/Transfer.svelte
- app/src/lib/wallet/cosmos/chain-info.ts
- typescript-sdk/playground/babylon-to-union-unwrap.ts
- typescript-sdk/playground/union-to-babylon-cw20.ts
- **feat(typescript-sdk): update playground to show approvals on ucs03 port addr**
- **feat(app): cw20 approvals on ucs03 contract**
- **feat(app): don't hardcode gasprices**
> Allow UCS03 to spend CW20s and don't hardcode gasPrice

- app/src/lib/components/TransferFrom/transfer/config.ts
- app/src/lib/components/address.svelte
- app/src/lib/components/token.svelte
- app/src/lib/components/transfer-details.svelte
- app/src/lib/stores/user.ts
- **fix(app): change default form fields**
- **feat(app): token details in tooltips**
- **feat(app): show token type**
- **fix(token): detail colors in light mode**
- **feat(app): linked denom addresses**
> Advanced Token Metadata hover view

- e2e/upgrades.nix
- flake.lock
- flake.nix
- networks/devnet.nix
- unionvisor/unionvisor.nix
- versions/versions.json
Prepare `bundle-testnet-9` for v0.26.0 of `uniond`
> feat(unionvisor): prepare update to bundle

- app/src/lib/chain-details.svelte
- app/src/lib/components/TransferFrom/components/Direction.svelte
- app/src/lib/components/footer.svelte
- app/src/lib/components/packet-path.svelte
- app/src/lib/stores/highlight.ts
- **feat(app): highlight chains**
- **fix(app): don't highlight chain in transfer details**
> Highlight chains in app

- docs/astro.config.ts
Moves "New Chain" up a level, just under "Connect"
> fix(docs): move new chain up in nav

- cosmwasm/ibc-union/lightclient/ethereum/src/client.rs
- cosmwasm/ibc-union/lightclient/ethereum/src/errors.rs
I was discussing this with @aeryz, and they asked me open a fix PR
> fix: identical misbehaviour headers

- app/app.nix
- app/package-lock.json
- app/package.json
- app/src/lib/components/TransferFrom/transfer/intents.ts
we still validate the address in validation.ts
> Fix receiver app

- lib/pg-queue/src/lib.rs
- voyager/plugins/transaction-batch/src/main.rs
since we requeue retryable errors with the same id (since 52e1a80fdd52d98f10b554b03aecf0248b160475), if there are many failing messages (due to a dead rpc, for example), all of the workers will be used to spin these failing messages. instead of ordering by id when popping an item from the queue, we now instead order by the created_at timestamp, and reinsert failed messages instead of simply rolling back the database transaction.
> fix(voyager): order item popping by timestamp, not id

- app/src/lib/components/InlineLoadingDots.svelte
- app/src/lib/components/TransferFrom/components/Cube/faces/Assets.svelte
- app/src/lib/components/TransferFrom/components/Cube/index.svelte
- app/src/lib/components/TransferFrom/components/TokenBalance.svelte
- app/src/lib/components/TransferFrom/index.svelte
- app/src/lib/components/TransferFrom/transfer/intents.ts
- app/src/lib/components/TransferFrom/transfer/types.ts
- app/src/lib/components/TransferFrom/transfer/validation.ts
- app/src/lib/components/balance-fetcher.svelte
- app/src/lib/components/token.svelte
- app/src/lib/stores/tokens.ts
- **fix(app): rework balance loading**
- **fix(app): don't persist tokeninfos**
- **fix(app): only fetch relevant balances**
- **fix(app): loading state for balance**
- **feat(app): show loading balances**
- **feat(app): better balance handling**
> Better balances fetching in app

- app/src/lib/components/TransferFrom/components/Cube/faces/Transfer.svelte
We should decide where we want to convert the receiver, most likely just move this into the sdk. But to get this out I suggest we merge this now.
> fix(app): fix receiver

- app/src/lib/components/chains-gate.svelte
- app/src/lib/graphql/fragments/transfers.ts
- app/src/lib/graphql/queries/chains.ts
- app/src/lib/graphql/queries/channels.ts
- app/src/lib/graphql/queries/transfer-details.ts
- app/src/lib/queries/channels.ts
- app/src/lib/types.ts
- **feat(app): optimize queries**
- **refactor(app): delete legacy assets**
> less wasteful queries

- cosmwasm/cosmwasm.nix
- cosmwasm/deployer/src/main.rs
- cosmwasm/ibc-union/app/ucs03-zkgm/Cargo.toml
- cosmwasm/ibc-union/app/ucs03-zkgm/src/contract.rs
- deployments/deployments.json
- lib/cosmos-client/src/lib.rs
also some zkgm fixes. use instantiate2 for minter and set the minter admin to zkgm itself
> cosmwasm deployer permissioned cosmwasm chains

- app2/src/app.css
- app2/src/app.html
- app2/src/lib/components/layout/AppErrors/index.svelte
- app2/src/lib/components/layout/Sidebar/index.svelte
- app2/src/routes/+layout.svelte
- **feat(app2): darkmode**
- **feat(app2): add sidebar**
- **feat(app2): sidebar navigation**
- **feat(app2): remove header**
- **feat(app): show global app errors**
> Sidebar layout with app errors section

- app2/src/lib/components/layout/Sidebar/index.svelte
- app2/src/lib/schema/address.ts
- app2/src/lib/schema/bech32.ts
- app2/src/lib/schema/chain.ts
- app2/src/lib/schema/hex.ts
- app2/src/lib/schema/transfer-list.ts
- app2/src/lib/stores/wallets.svelte.ts
- **fix(app2): type chain id and chain display name**
- **feat(app): add address types**
- **fix(app): correct wallet address types**
> Correct address types in app 2

- app2/README.md
- app2/src/lib/components/icons/SharpWalletIcon.svelte
- app2/src/lib/components/model/ErrorComponent.svelte
- app2/src/lib/components/ui/Button.svelte
- app2/src/lib/components/ui/Skeleton.svelte
- app2/src/lib/components/ui/Wallet/index.svelte
- app2/src/lib/queries/transfer-list-address.svelte.ts
- app2/src/lib/queries/transfer-list.svelte.ts
- app2/src/routes/explorer/transfers/+page.svelte
- app2/src/routes/transfers/+page.svelte
- **feat(app): add loading skeletons**
- **feat(app): proper skeletons**
- **feat(app): user-facing errors**
- **feat(wallet): add icon**
- **fix(app2): acquire fiber locks**
> Improve User-facing errors, add skeletons

- app2/CONVENTIONS.md
- app2/src/lib/components/SettingsModal.svelte
- app2/src/lib/components/icons/SharpCheckIcon.svelte
- app2/src/lib/components/icons/SharpContentCopyIcon.svelte
- app2/src/lib/components/model/BlockHashComponent.svelte
- app2/src/lib/components/model/TokenComponent.svelte
- app2/src/lib/components/model/TransactionHashComponent.svelte
- app2/src/lib/components/model/TransferListItemComponent.svelte
- app2/src/lib/components/ui/Truncate.svelte
- app2/src/lib/queries/transfer-by-hash.svelte.ts
- app2/src/lib/schema/packet-trace.ts
- app2/src/lib/schema/token.ts
- app2/src/lib/schema/transfer-details.ts
- app2/src/lib/schema/transfer-list.ts
- app2/src/lib/stores/settings.svelte.ts
- app2/src/lib/stores/transfer-details.svelte.ts
- app2/src/routes/explorer/transfers/+page.svelte
- app2/src/routes/explorer/transfers/[packet_hash]/+layout.ts
- app2/src/routes/explorer/transfers/[packet_hash]/+page.svelte
- app2/svelte.config.js
- **feat(app): show transfer details**
- **fix(app): purge stale transfer details**
- **feat(app): fetch full transfer details**
- **feat(app2): improved traces**
- **fix(app2): use chaincomponent in traces**
- **docs(app2): add CONVENTIONS.md**
- **docs(app2): add effect to conventions**
- **refactor(app2): packet-trace schema**
- **fix(app2): decode transfer amounts**
- **feat(app2): show base and quote tokens in transfer list**
- **feat(app2): add setting to toggle quoteToken visibility**
- **fix(app2): zinc color**
- **feat(app2): introduce TokenComponent**
- **feat(app): introduce truncate component**
- **fix(app2): tokencomponent order**
- **fix(app2): item widths**
- **feat(app2): more tokencomponent usage**
- **feat(app2): more hash components**
> Transfer Details page, many UX improvements

- app2/CONVENTIONS.md
- app2/src/lib/components/ui/Button.svelte
- app2/src/lib/components/ui/Input.svelte
- app2/src/lib/components/ui/Label.svelte
- app2/src/lib/services/transfer.ts
- app2/src/routes/transfer/+page.svelte
- **feat(app2): introduce input component**
- **fix(app2): use label as input label**
- **feat(app2): use button component in transfer**
- **docs(app2): more conventions**
- **fix(app2): Input and Label types**
- **feat(app2): effectful transfer submission**
- **feat(app2): refactor transfer submission**
- **feat(app2): improve transfer submission types**
- **feat(app): show interrupts**
- **fix: typo**
> Effectful transfer submission

- app2/src/lib/services/transfer.ts
- app2/src/lib/wallet/evm/config.svelte.ts
- app2/src/lib/wallet/evm/index.ts
- app2/src/lib/wallet/evm/wagmi-config.ts
- app2/src/routes/transfer/+page.svelte
- **refactor(app): move wagmi=config out of wallet/evm/config.svelte.ts**
- **feat(app2): switchChain effect**
- **feat(app2): switch chains, use connectorClient for tx submission**
- **chore(app2): cleanup**
> Switch chains and use connector clients in app2

- hubble/src/indexer/tendermint/block_handle.rs
Fixes https://github.com/unionlabs/union/issues/3915 by including events that are just "wasm" type
> Include wasm events in hubble indexing

- app2/src/lib/components/icons/OutlineControlPointDuplicate.svelte
- app2/src/lib/components/layout/Sidebar/navigation.ts
- app2/src/lib/components/model/TokenComponent.svelte
- app2/src/lib/components/ui/Tooltip.svelte
- app2/src/routes/explorer/tokens/+page.svelte
- **fix(app2): handle no representations on token**
- **feat(app2): tokens explorer page**
- **feat(app2): show multiple tokens per tokenexplorer row**
- **feat(app2): add tooltips**
- **feat(app2): improve token tooltip details**
- **feat(app2): better token tooltips**
- **fix(app2): tokens sidebar icon**
- **fix(app2): improve token tooltips**
- **fix(app2): tooltip positioning**
- **fix(app2): access tooltips with the mouse**
- **fix(app2): tooltip fixes**
- **fix(app2): tooltip timeouts**
> Tooltips, TokenComponent tooltip, token explorer

- app2/src/lib/components/layout/Sidebar/navigation.ts
- app2/src/lib/components/model/TokenComponent.svelte
- app2/src/lib/queries/tokens.svelte.ts
- app2/src/lib/schema/address.ts
- app2/src/lib/schema/chain.ts
- app2/src/lib/schema/token.ts
- app2/src/lib/stores/balances.svelte.ts
- app2/src/lib/stores/tokens.svelte.ts
- app2/src/routes/+layout.svelte
- app2/src/routes/balances/+page.svelte
- app2/src/routes/explorer/tokens/+page.svelte
- app2/src/routes/transfer/ucs03/+page.svelte
- **feat(app): balances sidebar**
- **feat(app2): add RawTokenBalance**
- **feat(app2): balances store**
- **fix(app2): improve balances store**
- **feat(app2): also key balances by address**
- **refactor(app2): use UniversalChainIds**
- **fix(app2): connected wallets log**
- **fix(app2): ban the use of : in chainids**
> Use UniversalChainIds in app2, store balances

- Cargo.lock
- cosmwasm/deployer/Cargo.toml
- cosmwasm/deployer/src/main.rs
- lib/cosmos-client/src/lib.rs
- lib/unionlabs/src/cosmos/auth/base_account.rs
- lib/unionlabs/src/signer.rs
also fixed submitting with a signer that doesn't exist on chain yet (i think?)
> feat: add functionality to create a bajillion signers

- app2/src/lib/components/ErrorsModal.svelte
- app2/src/lib/components/layout/AppErrors/index.svelte
- app2/src/lib/components/layout/Sidebar/index.svelte
- app2/src/lib/components/ui/Button.svelte
- app2/src/lib/stores/app-errors.svelte.ts
- app2/src/lib/stores/ui.svelte.ts
- app2/src/routes/+layout.svelte
- app2/src/routes/balances/+page.svelte
- app2/src/routes/dashboard/+page.svelte
- app2/src/routes/explorer/channels/+page.svelte
- app2/src/routes/explorer/clients/+page.svelte
- app2/src/routes/explorer/connections/+page.svelte
- app2/src/routes/explorer/packets/+page.svelte
- app2/src/routes/explorer/transfers/+page.svelte
- app2/src/routes/stake/+page.svelte
- app2/src/routes/transfer/+page.svelte
- app2/src/routes/transfer/ucs03/+page.svelte
- app2/src/routes/transfers/+page.svelte
- **feat(app2): begin build of header**
- **feat(app2): better error center**
- **feat(app2): show page title**
- **refactor(app2): use Option for pageName**
- **fix(app2): cleanup legacy titles**
> App2 header and error center

- .github/workflows/release-component.yml
Tested workflow up to actually releasing the binaries/images: https://github.com/unionlabs/union/actions/runs/13713369159
> fix(ci): correct workflow instructions

- app2/CONVENTIONS.md
- app2/src/lib/components/layout/Header/Breadcrumbs.svelte
- app2/src/lib/components/layout/Header/index.svelte
- app2/src/routes/+layout.svelte
- app2/src/routes/explorer/transfers/[packet_hash]/+page.svelte
- **refactor(app2): header component**
- **docs(app2): array syntax convention**
- **feat(app2): breadcrumbs component**
- **feat(app2): refine breadcrumbs**
> Add breadcrumbs to app2

- .github/workflows/release-component.yml
Successful run: https://github.com/unionlabs/union/actions/runs/13773228822
> feat(ci): update release workflow with bundle-union-1

- app2/src/lib/components/model/AddressComponent.svelte
- app2/src/lib/components/model/BlockHashComponent.svelte
- app2/src/lib/components/model/TokenComponent.svelte
- app2/src/lib/components/ui/Truncate.svelte
- app2/src/lib/schema/chain.ts
- app2/src/routes/explorer/transfers/[packet_hash]/+page.svelte
Will still be tweaked, will probably left-align tbh
- **feat(app2): optional truncate copy**
- **feat(app2): style transfer details page**
- **feat(app2): better display**
- **feat(app2): fancier from/to display**
- **feat(app2): more integrated times**
- **feat(app2): better transfer details styling**
> Better transfer details styling

- flake.lock
- unionvisor/unionvisor.nix
- update input
- fix unionvisor linking
> chore: update v1.0.0

- ts-sdk/package-lock.json
- ts-sdk/package.json
- ts-sdk/src/evm/abi/index.ts
- ts-sdk/src/evm/abi/ucs03.ts
- ts-sdk/test/evm.test.ts
- ts-sdk/ts-sdk.nix
- ts-sdk/tsconfig.json
- **fix(ts-sdk): update ucs03 abi**
- **chore(ts-sdk): allow for exporting sub-abis**
- **chore(ts-sdk): add effect**
- **fix(ts-sdk): update tests to new abi**
- **feat(ts-sdk): export subabis**
- **feat(ts-sdk): expose all subabis**
- **chore(ts-sdk): bump version and publish**
> Expose ucs03 struct abis in ts-sdk

- ts-sdk/README.md
- ts-sdk/examples/create-batch.ts
- ts-sdk/package-lock.json
- ts-sdk/src/evm/ucs03/index.ts
- ts-sdk/ts-sdk.nix
- **feat(ts-sdk): add create-batch example**
- **feat(ts-sdk): example for ben**
> TsSdk examples

- app2/src/lib/components/Transfer/index.svelte
- **feat(app2): check allowances**
- **feat(app2): list required approvals**
- **feat(app2): generate transfersteps**
> Generate transfer steps based on current allowances in app2

- evm/contracts/apps/ucs/03-zkgm/Lib.sol
- evm/contracts/apps/ucs/03-zkgm/Zkgm.sol
- evm/tests/src/05-app/Zkgm.t.sol
- introduce tests for fungible order verification
- audit: fix reverse channel path
> feat(zgkm): tests verify fungible order properties

- Cargo.lock
- Cargo.toml
- cosmwasm/cw20-token-minter/Cargo.toml
- cosmwasm/ibc-union/app/ucs03-zkgm/Cargo.toml
- cosmwasm/ibc-union/app/ucs03-zkgm/src/contract.rs
- cosmwasm/ibc-union/app/ucs03-zkgm/src/msg.rs
- cosmwasm/ibc-union/app/ucs03-zkgm/src/tests.rs
- evm/tests/src/05-app/Zkgm.t.sol
- start porting evm tests to aim for 1:1
> feat(zkgm): cosmwasm: test suite

- deployments/deployments-testnet-10.json
- deployments/universal-chain-ids.json
- **feat(deployment): add experimental bob and corn channels**
- **feat(universal-chain-ids): add bob and corn**
> Add experimental bob and corn channels

- app2/CONVENTIONS.md
- app2/src/lib/components/model/AddressComponent.svelte
- app2/src/lib/components/model/ChainComponent.svelte
- app2/src/lib/components/model/PacketComponent.svelte
- app2/src/lib/components/model/PacketTracesComponent.svelte
- app2/src/lib/components/model/TransactionHashComponent.svelte
- app2/src/lib/components/ui/Card.svelte
- app2/src/lib/components/ui/DateTimeComponent.svelte
- app2/src/lib/components/ui/Modal.svelte
- app2/src/lib/components/ui/Truncate.svelte
- app2/src/lib/constants/packet-trace-names.ts
- app2/src/lib/queries/packet-details.svelte.ts
- app2/src/routes/explorer/transfers/[packet_hash]/+page.svelte
- ts-sdk/src/schema/chain.ts
- ts-sdk/src/schema/packet.ts
- **refactor(app2): move packet traces to component**
- **fix: port**
- **feat(app2): cleaner transfer timeline**
- **fix(app2): cleaner packet trace**
- **feat(app2): better packet explorer**
- **feat(app2): wip sequence diagram**
- **fix(app2): tooltip alignment**
- **fix(app2): sequence type errors**
- **fix(app2): sequence alignments**
- **fix(app2): flatmap**
- **feat(app2): grid based sequence**
- **fix(app2): more grid fixes**
- **feat(app2): simplify trace**
- **feat(app2): even better packet trace**
- **fix(app2): dialog**
- **fix(app2): misc transfer detail fixes**
- **feat(app2): toggleable packet details**
- **fix(app2): polish transfer traces**
- **chore(app2): cleanup**
> App2 transfer/packet sequence diagram explorer

- evm/contracts/apps/ucs/03-zkgm/Zkgm.sol
- evm/contracts/apps/ucs/03-zkgm/ZkgmERC20.sol
- evm/evm.nix
- evm/scripts/Deploy.s.sol
- evm/tests/src/05-app/Zkgm.t.sol
- networks/services/forge.nix
- make handler/weth immutables
- avoid redundant encoding
> feat(zkgm): optimize

- app/src/lib/components/deprecation-notice.svelte
- app/src/lib/components/header/header.svelte
- app/src/routes/+layout.svelte
> Take app1 offline

- cosmwasm/deployer/src/main.rs
- cosmwasm/ibc-union/app/ucs03-zkgm/src/contract.rs
- cosmwasm/ibc-union/app/ucs03-zkgm/src/lib.rs
- cosmwasm/ibc-union/app/ucs03-zkgm/src/msg.rs
- cosmwasm/ibc-union/app/ucs03-zkgm/src/state.rs
- cosmwasm/ibc-union/app/ucs03-zkgm/src/tests.rs
- cosmwasm/ibc-union/app/ucs03-zkgm/src/token_bucket.rs
- cosmwasm/ibc-union/core/msg/src/msg.rs
- cosmwasm/ibc-union/core/src/contract.rs
- cosmwasm/ibc-union/core/src/lib.rs
- cosmwasm/ibc-union/core/src/state.rs
- cosmwasm/ibc-union/core/src/tests/channel/ibc_channel.rs
- cosmwasm/ibc-union/core/src/tests/client/ibc.rs
- cosmwasm/ibc-union/core/src/tests/connection/ibc.rs
- add rate limit operators on zkgm
- add whitelist based relayers on ibc-union
> feat(cosmwasm): ibc-union/zkgm access control

- evm/scripts/Deploy.s.sol
- manually prefix the namespace of lc/protoscols/libs to avoid any misusage
- add zkgmERC20 impl verification
- fix ctor args for constants provided at construction
> fix(evm): deploy: manual ns prefix, correct ctor args for verif

- app2/src/lib/components/Transfer/ChainAsset/ChainAssetButton.svelte
- app2/src/lib/components/icons/ArrowDownLeft.svelte
- app2/src/lib/components/model/AddressComponent.svelte
- app2/src/lib/components/model/ChainComponent.svelte
- app2/src/lib/components/model/PacketTracesComponent.svelte
- app2/src/lib/components/model/TokenComponent.svelte
- app2/src/lib/components/model/TransferListItemComponent.svelte
- app2/src/lib/components/ui/Sections.svelte
- app2/src/lib/constants/packet-trace-names.ts
- app2/src/routes/+layout.svelte
- app2/src/routes/explorer/transfers/[packet_hash]/+page.svelte
- **feat(app2):better wrappings design**
- **feat(app2): upgrade background video**
- **feat(app2): better styled tokencomponent**
- **fix(app2): token component fmt**
- **fix(app2): address component fmt**
- **feat(app2): add logos to chain component**
- **fix(app2): chain component 2**
- **feat(app2): don't show packetTraces in the transferdetails, only in packet details**
- **feat(app2): receive highlights**
- **feat(app2): packet arrow highlight**
- **feat(app2): polish traces**
- **fix(app2): sections gaps**
> App2 design improvements 7

- app2/src/lib/components/Transfer/pages/IndexPage.svelte
- app2/src/lib/components/icons/SpinnerIcon.svelte
- app2/src/lib/components/model/TokenComponent.svelte
- app2/src/lib/constants/settlement-times.ts
- app2/src/routes/explorer/transfers/[packet_hash]/+page.svelte
- show the "in progress" spinner and then the "completion checkmark". completion checkmark if we have the trace for the Ack
- define constants/settlement-delays.ts which contains Record<UniversalChainId, { SettlementContractUrl, SettlementInterval}>
- add lazy loading to assets
> ui changes

- app2/src/lib/components/ui/Modal.svelte
- app2/src/lib/utils/portal.ts
See https://web.archive.org/web/20240422024922/https://www.shaunchander.me/effective-modals-in-sveltekit.
> fix(app2): make modals spawn in portal

- ts-sdk/src/utils/index.ts
> chore: consolidate import statements

- cosmwasm/ibc-union/core/src/contract.rs
- cosmwasm/ibc-union/core/src/lib.rs
- evm/contracts/core/04-channel/IBCPacket.sol
- evm/contracts/core/Types.sol
- evm/tests/src/04-channel/IBCPacket.t.sol
- deprecate and block the usage of timeout height
> feat(ibc-union): deprecated height timeout

- cosmwasm/ibc-union/app/ucs03-zkgm/src/contract.rs
- cosmwasm/ibc-union/app/ucs03-zkgm/src/lib.rs
- cosmwasm/ibc-union/app/ucs03-zkgm/src/msg.rs
- cosmwasm/ibc-union/app/ucs03-zkgm/src/tests.rs
- evm/contracts/apps/ucs/00-pingpong/PingPong.sol
- evm/contracts/apps/ucs/03-zkgm/IZkgmable.sol
- evm/contracts/apps/ucs/03-zkgm/Lib.sol
- evm/contracts/apps/ucs/03-zkgm/Zkgm.sol
- evm/contracts/core/05-port/IIBCModule.sol
- evm/tests/src/05-app/Zkgm.t.sol
- allow order filling before finality
- disallow forwarding filling before finality
- update eureka module entrypoint to reflect the new operation `OnZkgm | OnIntentZkgm`
- thread more informations to eureka modules
> feat(zkgm): faster than finality market making

- app2/src/routes/health/+page.svelte
just quickly added this so its easier to know where to look in hubble, not sure we need to list it in navigation.
> feat(app2): show hubble colors

- voyager/plugins/transaction-batch/src/call.rs
- voyager/plugins/transaction-batch/src/callback.rs
- voyager/plugins/transaction-batch/src/data.rs
- voyager/plugins/transaction-batch/src/lib.rs
> feat(voyager): smarter batching

- app2/src/lib/components/layout/Sidebar/index.svelte
- app2/src/lib/components/layout/Sidebar/navigation.ts
- app2/src/lib/constants/faucets.ts
- app2/src/routes/faucet/+page.svelte
- tools/typescript/buildPnpmPackage.nix
- **feat(app2): external faucets page**
- **feat(app2): add google cloud faucet**
- **feat(app2): show nav items based on editions**
> External faucets page in app2

- cosmwasm/osmosis-tokenfactory-token-minter/src/contract.rs
- cosmwasm/osmosis-tokenfactory-token-minter/src/error.rs
> chore(osmosis-tokenfactory-token-minter): moar tests

- lib/voyager-message/src/lib.rs
- lib/voyager-message/src/module.rs
- lib/voyager-message/src/rpc.rs
- lib/voyager-message/src/rpc/server.rs
- voyager/modules/proof/cosmos-sdk-union/src/main.rs
- voyager/modules/proof/cosmos-sdk/src/main.rs
- voyager/modules/proof/ethereum/src/main.rs
- voyager/modules/proof/ethermint/src/main.rs
- voyager/modules/proof/movement/src/main.rs
- voyager/plugins/client-update/state-lens/src/main.rs
- voyager/plugins/packet-timeout/src/main.rs
- voyager/plugins/transaction-batch/src/call.rs
- voyager/plugins/zkgm-filter/src/main.rs
former is a prereq for sei support, latter will save us a lot of gas not relaying unnecessary acks
> feat(voyager): add support for missing proofs and fix zkgm filter plugin

- Cargo.lock
- lib/voyager-message/src/rpc/server.rs
- voyager/modules/state/ethereum/Cargo.toml
- voyager/modules/state/ethereum/src/main.rs
- voyager/plugins/transaction/ethereum/src/main.rs
- voyager/src/cli.rs
- voyager/src/main.rs
> Voyager more caching

- deployments/deployments.json
- evm/scripts/Deploy.s.sol
- fixup broken main
- upgrade holesky to latest main
> chore(evm): upgrade holesky to cutting edge

- lib/cosmos-client/src/gas/feemarket.rs
- networks/services/forge.nix
- fixes fee market rounding
- fixes deployments on devnet-eth
> fix(cosmos-client): fee market rounding

- uniond/app/ante.go
- uniond/app/post.go
- uniond/app/wasm.go
- uniond/go.mod
- uniond/uniond.nix
- Enabled the feemarket post handler
- Resolves issue where feemarket was not accounting for real gas consumption
prod-278-fee-market-rate-not-adjusted-when-block-space-is-full
> fix(uniond): enable fee market post handler

- voyager/plugins/event-source/movement/src/main.rs
i was unable to push to https://github.com/unionlabs/union/pull/4147, so this PR is just that PR plus some cleanup.
> fix(movement): use ibc_union_spec::log_event for logging events

- app2/src/lib/components/icons/RotateLeftIcon.svelte
- app2/src/lib/components/icons/SharpDoubleCheckIcon.svelte
- app2/src/lib/constants.ts
- app2/src/lib/queries/transfer-by-hash.svelte.ts
- app2/src/routes/explorer/transfers/[packet_hash]/+page.svelte
- ts-sdk/src/schema/packet.ts
- ts-sdk/src/schema/transfer-details.ts
- **feat(app2): basic status reporting**
- **fix(app2): use staging graphql on staging app site**
- **feat(app2): more statuses for transfer details**
- **feat(app2): double check for received & acked**
- **feat(app2): refund icons**
- **fix(app2): cleanup**
> Show acks and timeouts in transfer details

- app2/app2.nix
- app2/package.json
- app2/src/lib/components/NoWalletConnected.svelte
- app2/src/lib/components/model/ErrorComponent.svelte
- app2/src/lib/components/model/PacketTracesComponent.svelte
- app2/src/lib/components/ui/ConnectWalletButton.svelte
- app2/src/lib/components/ui/Wallet/connect/connection.svelte
- app2/src/lib/components/ui/Wallet/connect/index.ts
- app2/src/lib/queries/transfer-by-hash.svelte.ts
- app2/src/lib/services/cosmos/balances.ts
- app2/src/lib/services/shared/address.ts
- app2/src/lib/stores/balances.svelte.ts
- app2/src/lib/stores/packets.svelte.ts
- app2/src/lib/stores/sorted-balances.svelte.ts
- app2/src/lib/stores/transfer-details.svelte.ts
- app2/src/lib/transfer/multisig/components/SenderInput.svelte
- app2/src/lib/transfer/multisig/index.svelte
- app2/src/lib/transfer/multisig/services/filling.ts
- app2/src/lib/transfer/normal/index.svelte
- app2/src/lib/transfer/normal/services/filling.ts
- app2/src/lib/transfer/normal/steps/ApprovalStep.svelte
- app2/src/lib/transfer/normal/steps/CheckReceiverStep.svelte
- app2/src/lib/transfer/shared/components/Receiver.svelte
- app2/src/lib/transfer/shared/services/filling/check-allowance.ts
- app2/src/lib/transfer/shared/services/filling/create-context.ts
- app2/src/lib/transfer/shared/services/handlers/safe-hash.ts
- app2/src/lib/transfer/shared/services/multisig.ts
- app2/src/lib/utils/convert-display.ts
- app2/src/lib/utils/intercept-logos.ts
- pnpm-lock.yaml
Kept commits as small as possible for easy bisecting if requried.
> fix(app2): static analysis take 3

- .vscode/settings.json
- CONTRIBUTING.md
- README.md
- app2/CONVENTIONS.md
- evm/README.md
closes #4395
closes #4540
closes #4539
closes #4357
closes #3484
> rollup a bunch of small prs

- Cargo.lock
- Cargo.toml
- cosmwasm/ibc-union/core/Cargo.toml
- cosmwasm/ibc-union/core/msg/Cargo.toml
- cosmwasm/ibc-union/core/msg/src/lightclient.rs
- cosmwasm/ibc-union/core/msg/src/module.rs
- cosmwasm/ibc-union/core/msg/src/msg.rs
- cosmwasm/ibc-union/core/msg/src/query.rs
- cosmwasm/ibc-union/core/src/interface.rs
- cosmwasm/ibc-union/core/src/lib.rs
revival of #3508, which contained a merge commit, and rather than dealing with rebasing that i just cherrypicked the changes.
> feat(ibc-union): add cw-orch

- evm/tests/src/05-app/Zkgm.t.sol
- **Mixed V1/V2 batches** - Both order types in same transaction                
- **Cross-version tokens** - Same base token, different metadata = different    
wrapped tokens                                                                  
- **V1→V2 upgrades** - V2 can unwrap V1 tokens using compatibility mode         
- **Balance isolation** - V1 and V2 track outstanding balances separately       
- **V2 timeouts** - Proper refunds and balance cleanup for V2 orders            
- **Unwrap validation** - Rejects invalid baseAmount < quoteAmount scenarios
> feat(zkgm): more fao v1/v2 compat tests

- flake.lock
- flake.nix
- versions/versions.json
Updates v1.1.0 to point to v1.1.1 in bundles
> chore(unionvisor): prep v1.1.1 bundles

- uniond/docs/static/openapi.yml
- uniond/proto.nix
Exposes /cosmwasm/wasm endpoints in OpenAPI spec
> fix(uniond): expose wasmd api for node

- Cargo.lock
- lib/voyager-core/src/lib.rs
- lib/voyager-message/Cargo.toml
- lib/voyager-message/src/call.rs
- lib/voyager-message/src/data.rs
- voyager/plugins/event-source/cosmos-sdk/src/call.rs
- voyager/plugins/event-source/cosmos-sdk/src/main.rs
- voyager/plugins/event-source/ethereum/src/call.rs
- voyager/plugins/event-source/ethereum/src/main.rs
- voyager/plugins/event-source/sui/src/main.rs
- voyager/plugins/transaction-batch/src/call.rs
- voyager/src/cli.rs
- voyager/src/main.rs
small breaking change: `voyager init-fetch` -> `voyager index`
> feat(voyager): sdk improvements and range indexing support

- deployments/deployments.json
- tools/update-deployments/src/main.rs
hotfix to unblock token wrapping in hubble, will follow up with a proper fix soon
> fix(deployments): update osmosis mainnet token minter

- .github/workflows/deploy-docs.yml
- docs/src/content/docs/infrastructure/node-operators/nixos.mdx
While reading through the node operatior docs I saw information that was not up-to-date.
Enjoy! 🗿🗿🗿
> Fix nixos node operator closed source warning in docs

- flake.nix
- tools/rust/buildWasmContract.nix
- tools/rust/crane.nix
- tools/rust/rust.nix
current impl is a bit of a hack but works for now
> feat(crane): re-expose builders

- app2/src/lib/services/incentive.ts
- app2/src/routes/stake/+page.svelte
- **feat(app): add tax and commisions**
- **chore(app): fmt**
- **fix(app): use constant and get address dynamically from config**
> feat(app): tax and commision
