flake.nix
We broke aarch64 for devnet as we wanted to be able to deterministically build the evm contracts (sadly the solidity version we were building was yielding slightly different bytecodes). We reintroduce the old worlflow (aarch64 will build solidity).
=> fix(evm): build solidity for aarch64

.github/workflows/nightly.yml
Until we're able to stabilize the e2e test suite, we'll disable the nightly workflow
=> chore(ci): disable nightly workflow

app/src/app.html
> `<meta name="apple-mobile-web-app-capable" content="yes">` is deprecated
> Please include `<meta name="mobile-web-app-capable" content="yes">`
=> fix(app): update deprecated head meta tag

app/src/routes/transfer/(components)/transfer-form.svelte
in `ucs1_configurations` we renamed `forward` to `forwards` causing issues when selecting chain on transfer
=> fix(app): rename

.github/workflows/deploy-app.yml, app/app.nix
- uses correct ref on `push` trigger: https://github.com/unionlabs/union/actions/runs/10616457172/job/29426901095
=> fix(ci): provide backup sha when using garnix deploy

Cargo.lock, dictionary.txt, hubble/Cargo.toml, hubble/src/arb.rs, hubble/src/chain_id_query.rs, hubble/src/eth/client.rs, hubble/src/eth/fork.rs, hubble/src/eth/indexer.rs, hubble/src/race_client.rs, hubble/src/scroll.rs
This PR migrates Hubble from the ethers library to the alloy library for the following files:
arb.rs
chain_id_query.rs
client.rs
fork.rs
indexer.rs
scroll.rs
=> feat(hubble): migrate from ethers to alloy

docs/src/content/docs/joining-testnet/unionvisor.mdx, flake.nix, unionvisor/src/cli.rs, versions/versions.json
Adds the `set-binary` command to unionvisor enabling users to easily set the version of `uniond` being used by unionvisor. This allows users to more easily use tools like state sync and node snapshots.
Usage:
```shell
unionvisor --root $ROOT set-binary --bundle $BUNDLE $UNIOND_VERSION
```
=> feat(unionvisor): add set-binary command

dictionary.txt, docs/astro.config.ts, docs/src/content/docs/infrastructure/node-operators/nixos.mdx
missed the edit part in the url
`neofetch` is deprecated
=> chore: fix edit link in docs

ceremony/src/lib/components/Counter/index.svelte, ceremony/src/routes/+page.svelte, dictionary.txt
I had the wrong clock settings when doing the calculation. I believe we should use CEST, as we're still in the daylight saving period, and will continue to be on the 20th of September.
=> fix(ceremony): two hours wrong

Cargo.toml, devnet-compose/devnet-compose.nix, dictionary.txt, hubble/src/indexer/api.rs, hubble/src/indexer/dummy/dummy.rs, hubble/src/indexer/eth/context.rs, hubble/src/indexer/eth/fetcher_client.rs, hubble/src/indexer/fetcher.rs, hubble/src/indexer/mod.rs, lib/unionlabs/src/hash.rs
we eventually want to replace the `H*` types with this type (`H256` et al), but that is quite a hefty refactor so it will be done later. we're adding this type now to make movement integration easier (they have some interesting ser/de going on)
also fix some clippy lints that slipped through CI somehow
=> feat: add basis for new hash type

.github/workflows/deploy-app.yml, .github/workflows/deploy-ceremony.yml, .github/workflows/deploy-docs.yml
we want preview deployments to go through even if spellcheck, fmt, etc fails
=> chore: remove garnix preview deployment requirement

evm/contracts/clients/CometblsClient.sol, generated/rust/protos/src/union.ibc.lightclients.cometbls.v1.rs, lib/unionlabs/src/ibc/lightclients/cometbls.rs, lib/unionlabs/src/ibc/lightclients/cometbls/misbehaviour.rs, light-clients/cometbls-light-client/src/client.rs, light-clients/cometbls-light-client/src/errors.rs, uniond/proto/union/ibc/lightclients/cometbls/v1/cometbls.proto
- Use the correct height in `CometBLS` `Solidity` light client.
- Add misbehaviours to `ics08-movement`.
=> Small fix in Cometbls solidity light client and add misbehaviours to `ics08-cometbls`

app/src/routes/explorer/+layout.svelte, dictionary.txt
fixes #3084 
this solution is not perfect since it doesn't remove the applied style once the announcement is manually closed. The penalty is a little extra padding on bottom. But at least it makes nav buttons usable when there's an announcement
=> fix: pagination button visibility when there's alert

evm/contracts/core/04-channel/IBCPacket.sol, evm/contracts/core/24-host/IBCCommitment.sol, evm/tests/src/04-channel/IBCPacket.t.sol, evm/tests/src/core/Module.sol
- fixup `recvPacket` proof commitment key
- add more test variants for gas comparison
fixes #3110
=> feat(evm): fix commitment & more test variants

cosmwasm/ucs01-relay/Cargo.toml, cosmwasm/ucs01-relay/src/protocol.rs
following #3103 
- use native cosmwasm async ack instead of our own (now ditched) deffered ack module
=> fix(cosmwasm): use cosmwasm `WriteAcknowledgement`

cosmwasm/ucs01-relay/src/ibc/tests.rs, cosmwasm/ucs01-relay/src/protocol.rs, lib/ibc-events/src/lib.rs, lib/ibc-vm-rs/src/lib.rs, lib/ibc-vm-rs/src/states/channel_handshake.rs, lib/ibc-vm-rs/src/states/connection_handshake.rs, lib/ibc-vm-rs/src/states/packet.rs, lib/ics23/src/ibc_api.rs, lib/ics23/src/verify.rs, lib/macros/src/lib.rs, lib/near/dummy-ibc-app/src/contract.rs, lib/near/near-ibc/src/contract.rs, lib/unionlabs/src/cosmwasm/wasm/union/custom_query.rs, lib/unionlabs/src/ethereum.rs, lib/unionlabs/src/ibc/core/channel/channel.rs, lib/unionlabs/src/ibc/core/channel/counterparty.rs, lib/unionlabs/src/ibc/core/channel/packet.rs, lib/unionlabs/src/ibc/core/client/height.rs, lib/unionlabs/src/ibc/core/connection/counterparty.rs, lib/unionlabs/src/ics24.rs, lib/unionlabs/src/id.rs, lib/unionlabs/src/lib.rs, lib/voyager-message/src/call.rs, lib/voyager-message/src/data.rs, light-clients/arbitrum-light-client/types/src/client_state.rs, voyager/plugins/event-source/movement/src/main.rs, voyager/plugins/transaction/aptos/src/main.rs, voyager/src/cli.rs, voyager/src/main.rs
[parse, don't validate](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/)
- connection and channel id are now just u32
- both have `from_str_prefixed` constructors, as well as alternate display formatting (via `{:#}`) and a `to_string_prefixed` method to emulate the old behaviour
- port id is as per the ics24 specification (same as it was previously, but no longer using `Validated`)
- client id is now a tuple of (prefix, id)
- note that it is *not* client type as the prefix, as that is not necessarily true - see `08-wasm`
- added alternate display formatting to `Height` to always display the revision number, even if it's zero
- a bit of hacking on `#[ibc_path]`, this will be deprecated soon so don't look too hard at it
- disabled some voyager commands temporarily, they …
=> feat: refactor id types

generated/rust/protos/src/union.ibc.lightclients.ethereum.v1.rs, light-clients/ethereum-light-client/src/client.rs, light-clients/ethereum-light-client/types/src/client_state.rs, light-clients/ethereum-light-client/types/src/light_client_update.rs, light-clients/ethereum-light-client/types/src/light_client_update_data.rs, uniond/proto/union/ibc/lightclients/ethereum/v1/ethereum.proto, voyager/modules/consensus/ethereum/src/main.rs
This fix involves:
1. Adding chain spec to the client state and branching off based on that during verification.
2. Removing unnecessary fields from the client state.
3. Fixing misbehaviour and minor improvements to the client.
=> Further fixes to the ethereum light client

.gitattributes, app/src/lib/queries/balance/evm/multicall.ts, biome.json, ceremony/src/lib/utils/utils.ts, dictionary.txt, flake.nix, site/src/lib/contentful/live-preview.ts
previous pr i forgot to run fmt + i added deno cause jsr publishing requires it
=> chore: fmt and add pkg

hubble/src/beacon.rs, hubble/src/indexer/tm/fetcher_client.rs
beacon implementation was inspecting response body to detect there was no block. the response body of the endpoint changed (returning `{"code":404,"message":"No block found for id '4845861'"}`).
change it to use the http response code (also kept original implementation, because we're not sure if all rpc behave like this)
=> Hubble fix baecon no block handling

cosmwasm/union-ibc/core/src/contract.rs
- **fix(union-ibc): remove redundant to_vec calls**
- **fix(union-ibc): simplify proof_commitment_key**
=> Minor union-ibc cleanup

.envrc, .gitattributes, .gitignore, .vscode/extensions.json, .vscode/settings.json, .vscode/tasks.json, biome.json, devShell.nix, flake.lock, flake.nix, site/public/manifest.webmanifest, treefmt.nix
how to run this:
```sh
nix run github:nixos/nixpkgs/nixpkgs-unstable#openvscode-server -- \
--disable-telemetry \
--host="127.0.0.1" \
--accept-server-license-terms \
--update-extensions \
--start-server
```
with this setup and the declared vscode extensions, we end up with the following:
nix lsp support in vscode that runs from a NixOS vm (through OrbStack)
as well as lsp support for astro, svelte, typescript and svelte (and whatever else im forgetting)
ability to run dev within the vscode web app and launch an embdded browser
=> feat: openvscode-server nix setup

flake.nix
httpie includes the cacert package, which ignores certificates installed on the system, which is not desirable.
xh is a rust-clone of httpie
=> fix(hubble): replace httpie with xh

evm/evm.nix, evm/tests/src/02-client/CometblsClient.t.sol, evm/tests/src/02-client/CosmosInCosmosClient.t.sol, evm/tests/src/05-app/ERC20Denom.t.sol, evm/tests/src/05-app/ERC721Denom.t.sol, evm/tests/src/05-app/NFT.t.sol, evm/tests/src/05-app/Relay.t.sol, evm/tests/src/core/ERC20Denom.sol, evm/tests/src/core/Relay.sol, evm/tests/src/lib/ICS23.t.sol
Increased solidity test coverage to +80%.
Final coverage:
Coverage on main:
=> Improved new evm test cases

lib/aptos.nix, lib/evm-storage-verifier/src/error.rs, lib/evm-storage-verifier/src/lib.rs, lib/evm-storage-verifier/src/rlp_node_codec.rs, lib/unionlabs/src/hash.rs
Fixes https://github.com/unionlabs/union/issues/3363
Since Unionlabs::Hash::H256 is already implemented, this refactors the codes that uses primitive_types::H256 to our own one.
Additionally ,this PR implements AsMut to hash.rs as Hasher need AsMut trait to be resolved.
=> Refactor: Use h256 from own crate in evm storage verifier

lib/voyager-core/src/lib.rs, lib/voyager-message/src/call.rs, lib/voyager-message/src/module.rs, lib/voyager-message/src/rpc.rs, lib/voyager-message/src/rpc/server.rs, voyager/modules/client/cometbls/src/main.rs, voyager/modules/client/ethereum/src/main.rs, voyager/modules/client/movement/src/main.rs, voyager/modules/client/tendermint/src/main.rs, voyager/modules/consensus/cometbls/src/main.rs, voyager/modules/consensus/ethereum/src/main.rs, voyager/modules/consensus/movement/src/main.rs, voyager/modules/consensus/tendermint/src/main.rs, voyager/modules/state/movement/src/main.rs, voyager/plugins/client-update/ethereum/src/main.rs
closes #3388
This PR implements new Timestamp type under voyager core, unifying types that express time as nanoseconds
=> feat(voyager): replace u64 timestamp with Timestamp type across modules

.helix/languages.toml, evm/package-lock.json, evm/package.json
Language server provided by `solc` has long been broken, so I used
https://www.npmjs.com/package/vscode-solidity-server .
I tried packaging it, but node-gyp blocked me: https://github.com/NixOS/nixpkgs/issues/370370.
Config in this PR works, but does require you to run `npm install` in `evm/` once to get the solidity lsp.
=> feat(helix): configure vscode-solidity-server

.github/workflows/typescript-sdk-preview.yml, app/src/lib/constants/index.ts, app/src/lib/wallet/evm/config.ts, typescript-sdk/package.json, typescript-sdk/playground/holesky-to-sepolia.ts, typescript-sdk/playground/sepolia-to-holesky.ts, typescript-sdk/src/abi/index.ts, typescript-sdk/src/abi/ucs-03.ts, typescript-sdk/src/aptos/client.ts, typescript-sdk/src/cosmos/client.ts, typescript-sdk/src/evm/client.ts, typescript-sdk/src/evm/transfer.ts, typescript-sdk/src/pfm.ts, typescript-sdk/src/query/offchain/hubble.ts, typescript-sdk/src/query/offchain/tenderly.ts
Still rather messy, but enough to unblock app and indexing development
- **feat(typescript-sdk): add ucs03 abi**
- **refactor(typescript-sdk): use ucs03 for transfers**
- **feat(typescript-sdk): randomize salt**
=> Use UCS03 in TypeScript SDK

app/src/lib/components/TransferFrom/components/Cube/faces/Assets.svelte, app/src/lib/components/TransferFrom/components/Cube/faces/Intent.svelte, app/src/lib/components/TransferFrom/components/Cube/faces/Transfer.svelte, app/src/lib/components/TransferFrom/components/Direction.svelte, app/src/lib/components/TransferFrom/components/SelectedAsset.svelte, app/src/lib/components/TransferFrom/index.svelte, app/src/lib/components/TransferFrom/transfer/balances.ts, app/src/lib/components/TransferFrom/transfer/context.ts, app/src/lib/components/TransferFrom/transfer/index.ts, app/src/lib/components/TransferFrom/transfer/intents.ts, app/src/lib/components/TransferFrom/transfer/schema.ts, app/src/lib/components/TransferFrom/transfer/validation.ts, app/src/lib/queries/balance/index.ts, app/src/routes/transfer/+page.svelte
Since the stores rely on rawIntents, propagated values can be undefined. However, when validation is valid, we know all values are correct and available. We could of course work with default values to never have source and destination undefined. Selected asset, receiver and amount cant be set to a default value tho. 
so now we have
```js
export type FieldErrors = Partial<Record<keyof FormFields, string>>
export interface ValidTransfer {
sourceChain: Chain
destinationChain: Chain
asset: {
address: string
balance: bigint
symbol: string
decimals: number
gasToken: boolean
supported: ChainAsset
}
receiver: string
amount: string
}
export interface InvalidValidationStore {
transfer: undefined
errors: FieldErrors
isValid: false
}
export interface ValidValidationStore {
transfer: ValidTransfer …
```
=> refactor(app): changes to stores

typescript-sdk/src/abi/ucs-03.ts, typescript-sdk/src/evm/client.ts, typescript-sdk/src/evm/transfer.ts
- **fix(typescript-sdk): update ucs-03.ts**
- **fix(typescript-sdk): update transfer abi args**
=> update typescript abi

app/src/lib/components/table-cells/cell-sequence.svelte, app/src/lib/components/tables/packets.svelte, app/src/lib/graphql/fragments/packets.ts, app/src/lib/queries/packets.ts
- **fix(app): basic packet fetching**
- **feat(app): fetch ibc-union packets**
=> Fetch ibc-union packet list in app

networks/e2e-setup.nix, voyager/config.json, voyager/modules/client-bootstrap/ethereum/src/main.rs, voyager/modules/consensus/berachain/src/main.rs, voyager/modules/consensus/ethereum/src/main.rs, voyager/modules/proof/ethereum/src/main.rs, voyager/modules/state/ethereum/src/main.rs, voyager/plugins/client-update/berachain/src/main.rs, voyager/plugins/client-update/ethereum/src/main.rs, voyager/plugins/event-source/ethereum/src/main.rs, voyager/plugins/transaction/ethereum/src/main.rs
also denied unwraps in the eth state module
=> chore(voyager): clean up eth rpc config param naming

lib/ibc-union-spec/src/lib.rs, lib/voyager-message/src/call.rs, lib/voyager-message/src/lib.rs, lib/voyager-message/src/rpc.rs, lib/voyager-message/src/rpc/server.rs, voyager/plugins/client-update/berachain/src/main.rs, voyager/plugins/client-update/ethereum/src/call.rs, voyager/plugins/client-update/ethereum/src/main.rs, voyager/plugins/client-update/state-lens/src/call.rs, voyager/plugins/client-update/state-lens/src/main.rs, voyager/plugins/periodic-client-update/src/main.rs, voyager/plugins/transaction-batch/src/call.rs, voyager/src/cli.rs, voyager/src/main.rs
internal voyager change to add the client id of the client being updated to the update client request message, such that update plugins can inspect the client state for possible client-specific configuration options.
=> feat(voyager): make the state lens client update module fully generic

.github/workflows/release-component.yml
Sample release: https://github.com/unionlabs/union/releases/tag/v0.25.0
Docker images: https://github.com/unionlabs/union/pkgs/container/bundle-testnet-9
=> 3346 revamp release component workflow to remove nixbuildnet

docs/src/content/docs/integrations/api/graphql.mdx
Fixed links to the [ethereum.org](https://ethereum.org) docs that weren't linking correctly!
=> docs(integrations): fix broken links

app/app.nix, app/package-lock.json, app/package.json, app/src/lib/components/TransferFrom/components/Cube/faces/Intent.svelte, app/src/lib/components/TransferFrom/index.svelte
- **feat(app): wip quote token msg**
- **feat(app): show no quote token available message**
- **chore(app): fmt**
=> Show no quote token available in app

README.md
Due to the  [refactor of the light client directory structure](https://github.com/unionlabs/union/pull/3266/commits/5b167c8e25f1e65f6a120f04dbd9763b69de6012) from pull request #3266 the link `./light-clients` needs to update to `./cosmwasm/ibc-union/light-clients`
=> chore: correct README link due to changes from PR #3266

docs/astro.config.ts, docs/src/content/docs/connect/app/asset-transfer/cosmwasm.mdx, docs/src/content/docs/connect/app/asset-transfer/index.mdx, docs/src/content/docs/connect/app/asset-transfer/solidity.mdx, docs/src/content/docs/connect/app/custom-data/index.mdx, docs/src/content/docs/connect/app/index.mdx, docs/src/content/docs/connect/new-chain.mdx
- ~~ucs03 Data Transfer - CosmWasm~~ (#3622)
- ~~ucs03 Data Transfer - Solidity~~ (#3622)
- ~~Connecting New Chains~~ (#3465)
=> Add developer docs for connecting apps

hubble/src/indexer/fetcher.rs, hubble/src/indexer/finalizer.rs, hubble/src/indexer/fixer.rs
there are three indexing flows (for each chain): fetching, finalizing and fixing. The indexer (for a chain) is restarted in case of an error. This is a problem if a chain has rpcs with a high error rate, because the restart kills all transactions.
This PR changes this, so errors in each flow are handled individually.
=> Hubble prevent restart on error

.github/workflows/check.yml, .github/workflows/deploy-app.yml, .github/workflows/deploy-ceremony.yml, .github/workflows/deploy-docs.yml, .github/workflows/deploy-zkgm-dev.yml, .github/workflows/typescript-sdk-publish.yml
Use `github.ref` for concurrency as recommended by the [official concurrency docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs)
=> fix(ci): use github.ref for concurrency

app/src/routes/faucet/+page.svelte
they relied on a deprecated assets table
=> Disable external faucets

aptos/ibc/sources/cometbls_lc.move, aptos/ucs03-zkgm/sources/fungible_asset_order.move, aptos/ucs03-zkgm/sources/token_denom.move, aptos/ucs03-zkgm/sources/zkgm.move, cosmwasm/cw20-token-minter/src/contract.rs, cosmwasm/ibc-union/app/ucs03-zkgm/src/com.rs, cosmwasm/ibc-union/app/ucs03-zkgm/src/contract.rs, cosmwasm/ucs03-zkgm-token-minter-api/src/lib.rs, evm/contracts/apps/ucs/03-zkgm/Zkgm.sol, evm/contracts/apps/ucs/03-zkgm/ZkgmERC20.sol
- Add decimals to `FungibleAssetOrder` and make it V1.
- `move` implementation dropped support for `FungibleAssetOrderV0`.
- `cosmwasm` and `evm` implementations are backwards compatible with `FungibleAssetOrderV0`.
- All implementations now default to `FungibleAssetOrderV1` in their `transfer` function.
- Fixed a bug where we don't handle minimum lengths in symbols and names in `cw20`.
- Added names and symbols to the `move` impl.
=> zkgm: better name and symbol handling, and handle decimals

app2/src/app.html, app2/src/lib/components/ChainList.svelte, app2/src/lib/components/layout/AppErrors/index.svelte, app2/src/lib/components/layout/Sidebar/index.svelte, app2/src/lib/components/model/ChainComponent.svelte, app2/src/lib/components/model/ErrorComponent.svelte, app2/src/lib/components/ui/Card.svelte, app2/src/lib/components/ui/Label.svelte, app2/src/lib/components/ui/Sections.svelte, app2/src/lib/queries/chains.svelte.ts, app2/src/lib/queries/transfer-list.svelte.ts, app2/src/lib/schema/chain.ts, app2/src/routes/+layout.svelte, app2/src/routes/explorer/transfers/+page.svelte
I'll have to think of how to make the pagination more generic and DRY, but getting this merged so that we have a transfers list to experiment with.
- **feat(app2): introduce card component**
- **fix(app): layout overflow issue, introduce sections**
- **feat(app): fetch transfer and show details**
- **feat(app2): load transfers with skeletons**
- **feat(app): better transfers layout**
- **feat(app2): pagination controler**
- **fix(app2): transfers layout shift**
- **feat(app): implement pagination**
- **feat(app): paginate forwards and backwards**
- **feat(app): live, next, prev pages**
=> Smooth paginated transfers UI

tools/rust/crane.nix
this actually reduces the size of all rust builds, but the size improvements aren't as important for non-wasm builds.
=> feat(wasm): reduce size of built wasm blobs

cosmwasm/ibc-union/core/msg/src/lightclient.rs, cosmwasm/ibc-union/core/src/contract.rs, cosmwasm/ibc-union/core/src/lib.rs
Wrap light client query failures to avoid the opaque wasmd query error code.
=> chore(ibc-union): more precise error in case of lc query failure

evm/contracts/apps/ucs/03-zkgm/Zkgm.sol, evm/tests/src/05-app/Zkgm.t.sol
Refactor the forward instruction to wrap the entire path, on execution we dequeue the intermediate channel from the path and either re-yield the forward packet with the tail of the path or yield the embedded instruction if we are reaching the destination (we just executed the final hop).
```
exec(zkgm([...], forward([x, y], i))) = send(y, zkgm([..., x, y], i))
exec(zkgm([...], forward([x, y, cont], i))) = send(y, zkgm([..., x, y], forward([cont], i)))
```
=> feat(zkgm): simplify forward instruction and introduce more tests

cosmwasm/ibc-union/core/src/contract.rs, cosmwasm/ibc-union/core/src/lib.rs, cosmwasm/ibc-union/core/src/tests/client/ibc.rs, evm/contracts/apps/ucs/00-pingpong/PingPong.sol, evm/contracts/apps/ucs/03-zkgm/IEurekaModule.sol, evm/contracts/apps/ucs/03-zkgm/Zkgm.sol, evm/contracts/core/04-channel/IBCPacket.sol, evm/contracts/core/Types.sol, evm/tests/src/04-channel/IBCPacket.t.sol, evm/tests/src/05-app/Zkgm.t.sol, lib/ibc-union-spec/src/path.rs
Improve zkgm handling of forward in-flight packet check by masking the forwarded salt and checking it (avoids 2 sload in ack/timeout if the packet isn't a forward (100% of current packets).
Introduce the `path` and `source`/`destination` channel on multiplexed calls for the target protocol to have the full packet context when being executed.
Upgrade IBC-Union to prevent ack replay (fixes #3794).
=> zkgm improvements / ibc-union upgrade

docs/src/content/docs/architecture/cometbls.mdx, docs/src/content/docs/concepts/bls-signatures.mdx
The expression of BLS signatures and verifications is wrong and make them correct.
=> chore: fix semantic expression of BLS cryptography

tools/devnet-utils/src/main.rs
This PR updates deprecated `#[clap(...)]` attributes to their modern equivalents in `clap` 4.x.
The current codebase still uses outdated syntax that has been deprecated since version 4.0.
By making this update, we ensure compatibility with future versions and maintain code quality.
=> fix: deprecated #[clap] attributes with #[arg] and #[command]

cosmwasm/ibc-union/app/ucs03-zkgm/src/contract.rs, cosmwasm/ibc-union/app/ucs03-zkgm/src/lib.rs, cosmwasm/ibc-union/app/ucs03-zkgm/src/state.rs, evm/contracts/apps/ucs/03-zkgm/Zkgm.sol
Also add some assertions on the batch acknowledgements to make sure upgrades don't break the semantic.
=> fix(zkgm): revert batch if any instruction require a market maker

cosmwasm/ibc-union/core/src/contract.rs, evm/contracts/core/04-channel/IBCPacket.sol, evm/tests/src/04-channel/IBCPacket.t.sol, evm/tests/src/core/IBCHandler.sol
- ensure that the batched packets share the same channel, avoiding a malicious client from accepting a batch that would result in arbitrary packets indexed at i+1 to be accepted by the protocol
=> fix(ibc-union): ensure batches share the same channel

evm/tests/src/05-app/Zkgm.t.sol
Due to hash properties, the forward tinting mechanism has false positive but no false negative. Avoid the false positive by forcing the salt to be not tinted in tests.
=> fix(zkgm): better zkgm forward salt tinting

evm/contracts/apps/ucs/00-pingpong/PingPong.sol, evm/contracts/apps/ucs/03-zkgm/Zkgm.sol, evm/contracts/clients/CometblsClient.sol, evm/contracts/clients/StateLensIcs23Ics23Client.sol, evm/contracts/clients/StateLensIcs23MptClient.sol, evm/contracts/clients/StateLensIcs23SmtClient.sol, evm/contracts/core/25-handler/IBCHandler.sol
Ensure the transfer of owned contracts is two-step. Allowing the admin to nominate and new admin to claim, avoiding a one-step transfer to a wrong address.
=> feat(evm): two-step transfer process for owned contracts

voyager/modules/consensus/tendermint/src/main.rs
Fix logical discrepancy in Tendermint consensus module's timestamp query
While studying the Union project's implementation of various consensus modules, I noticed a logical discrepancy in the Tendermint module's implementation of `query_latest_timestamp`.
The current implementation has a condition that contradicts the log message and the intended behavior. The code currently reads:
```rust
if finalized && commit_response.canonical {
trace!(
"commit is not canonical and finalized timestamp was \\
requested, fetching commit at previous block"
);
// ... fetch previous block logic ...
}
```
This is inconsistent with the log message which states "commit is not canonical" while the condition checks if it IS canonical. This also contradicts the implementation of `latest_height` which correctly …
=> fix: correct condition in Tendermint's query_latest_timestamp

app2/src/lib/components/Transfer/Amount.svelte, app2/src/lib/components/Transfer/pages/FillingPage.svelte, app2/src/lib/components/ui/Input.svelte, app2/src/lib/services/shared/amount.ts
- supports cross-browser
- allows '.' or ',' for internationalization
- disallows leading zeroes
=> fix(app2): validate amount input correctly

app2/src/lib/components/model/TransferListItemComponent.svelte, app2/src/lib/services/aptos/balances.ts, app2/src/lib/services/aptos/clients.ts, app2/src/lib/services/cosmos/balances.ts, app2/src/lib/services/evm/balances.ts, app2/src/lib/stores/app-errors.svelte.ts, app2/src/lib/stores/balances.svelte.ts, app2/src/lib/transfer/normal/steps/ApprovalStep.svelte, app2/src/lib/transfer/normal/steps/SubmitStep.svelte, app2/src/lib/transfer/shared/components/ChainAsset/ChainAssetButton.svelte, app2/src/routes/explorer/transfers/[packet_hash]/+page.svelte, app2/src/routes/transfers/+page.svelte, package.json, pnpm-lock.yaml, ts-sdk/package.json, ts-sdk/src/schema/chain.ts, ts-sdk/ts-sdk.nix
Fixes the following classifications of static analysis errors:
- Direct `value` property access of `Option<T>` types which have not been narrowed to `Some<T>`
=> chore(app2,ts-sdk): cleanup static analysis #1

app2/src/lib/services/cosmos/chain-info/configs/index.ts, app2/src/lib/services/cosmos/chain-info/configs/keplr/index.ts, app2/src/lib/services/cosmos/chain-info/configs/leap/index.ts, app2/src/lib/wallet/cosmos/chain-info.ts
We have duplicates, we should use whatever is in `/services/cosmos/chain-info,` will refactor in next pr.
=> feat(app2): add xion chain config

flake.nix
Removes garnix cache from the flake/devshell. Be sure to also remove it from your system flake configured substitutes
=> chore: disable garnix cache

app2/src/lib/components/model/ErrorComponent.svelte, app2/src/lib/components/model/InsetError.svelte, app2/src/lib/copy.ts, app2/src/lib/services/cosmos/chain-info/index.ts, app2/src/lib/services/evm/clients.ts, app2/src/lib/services/transfer-ucs03-cosmos/chain.ts, app2/src/lib/services/transfer-ucs03-cosmos/errors.ts, app2/src/lib/services/transfer-ucs03-evm/chain.ts, app2/src/lib/services/transfer-ucs03-evm/errors.ts, app2/src/lib/services/transfer-ucs03-evm/machine.ts, app2/src/lib/services/transfer/chain.ts, app2/src/lib/services/transfer/errors.ts, app2/src/lib/transfer/normal/services/filling.ts, app2/src/lib/transfer/normal/steps/ApprovalStep.svelte, app2/src/lib/transfer/normal/steps/FillingStep.svelte, app2/src/lib/transfer/normal/steps/SubmitStep.svelte, app2/src/lib/transfer/shared/errors/index.ts, app2/src/lib/transfer/shared/services/filling/check-allowance.ts, app2/src/lib/transfer/shared/services/filling/check-balance.ts, app2/src/lib/transfer/shared/services/write-cosmos.ts, app2/src/lib/transfer/shared/services/write-evm.ts, app2/src/lib/types.ts, app2/src/lib/utils/interpolate.ts, app2/tsconfig.json
- Full rewrite of EVM and Cosmos transaction FSMs for the sake of type clarity. No more `Promise` and `Exit` usage until execution boundary.
- Fixes to CTA button copy not being updated separately for EVM and Cosmos in Approval and Submit steps.
- All errors now discriminable and tracked at the type level in Approval and Submit steps.
- `<ErrorComponent />` additions to guarantee every provided error has a corresponding human-readable message. <sub>_(also reintroduction of this component in the transfer flow to replace "Error" CTA)_<sub>
- An extraordinary amount of exhaustive matching.
- Unfinished interpolation functions for dynamic copywrite.
- `SwitchChainError` is now a sum type containing `EvmSwitchChainError` and `CosmosSwitchChainError` to serve as an example moving forward, such …
=> feat(app2): improve user-facing errors

flake.nix
was meant to fix `forge` in devshell. will be changed to a wrapper
around forge
=> fix: do not set LD_LIBRARY_PATH

evm/contracts/apps/ucs/03-zkgm/Lib.sol, evm/contracts/apps/ucs/03-zkgm/Store.sol, evm/tests/src/05-app/Zkgm.t.sol
Introduce staking tests
- test_verify_stake_ok - Valid staking with governance token transfer and NFT minting                                                                                                
- test_verify_unstake_ok - Valid unstaking from STAKED state with NFT escrow                                                                                                         
- test_verify_withdrawStake_ok - Valid withdrawal after unstaking completion time                                                                                                    
- test_verify_withdrawRewards_ok - Valid reward withdrawal from STAKED position                                                                                                 
- test_verify_stake_invalidGovernanceToken - Rejects …
=> feat(zkgm): introduce stake/unstake/withdrawStake/withdrawRewards tests

app2/src/lib/dashboard/components/AccountInfo.svelte, app2/src/lib/dashboard/components/DeleteAccountModal.svelte, app2/src/lib/dashboard/components/SocialConnections.svelte, app2/src/lib/dashboard/components/UnlinkAccountModal.svelte
- Added confirmation modals for both account deletion and social account unlinking
- Both modals implement a two-step confirmation process with security measures
- Users must type specific confirmation text to proceed with destructive actions
- Created `DeleteAccountModal.svelte` component
- Users must type their account ID to confirm deletion
- 5-second countdown timer before final deletion
- Updated `AccountInfo.svelte` to use the modal
- Created `UnlinkAccountModal.svelte` component
- Users must type "unlink {provider} and delete my xp" to confirm
- Same two-step flow and countdown timer as deletion modal
- Updated `SocialConnections.svelte` to use the modal instead of direct unlinking
- Clear warnings about losing rewards and XP permanently
=> feat(app): Add confirmation modals for account deletion and social unlinking

Cargo.lock, Cargo.toml, cosmwasm/cosmwasm.nix, cosmwasm/cw-escrow-vault/Cargo.toml, cosmwasm/cw-escrow-vault/README.md, cosmwasm/cw-escrow-vault/src/contract.rs, cosmwasm/cw-escrow-vault/src/error.rs, cosmwasm/cw-escrow-vault/src/lib.rs, cosmwasm/cw-escrow-vault/src/msg.rs, cosmwasm/cw-escrow-vault/src/state.rs, cosmwasm/ibc-union/app/ucs03-zkgm/src/com.rs, cosmwasm/ibc-union/core/src/state.rs, lib/depolama/src/key.rs, lib/depolama/src/value.rs
A CosmWasm contract that acts as a solver in the zkgm protocol, enabling fungible token transfers across IBC channels by managing escrowed assets.
Key Features
- Dual Token Support: Handles both native Cosmos tokens (via BankMsg) and CW20 tokens
- Fungible Lane Configuration: Maps (channel_id, base_token) pairs to counterparty beneficiaries for cross-chain settlement
- Intent Whitelisting: Controls which packet hashes can be filled before finality
- Solver Interface: Implements DoSolve to release escrowed tokens and return beneficiary addresses for acknowledgments
How It Works
1. Admin configures fungible lanes linking channels/tokens to counterparty beneficiaries
2. When zkgm calls DoSolve, the contract validates the order and releases escrowed tokens
3. Relayers receive fees …
=> feat(cosmwasm): introduce escrow vault for fungibility layer

hubble/src/indexer/enricher.rs
currently hubble stops enricher when 'draining', but it shouldn't. 
background: drain should flush all indexed events on the 'indexing' side (the part that'll run in spitzer). when migrating, we'll first start draining, to ensure no events in hubble are in-flight, then we'll migrate the hubble state into spitzer and start spitzer which will do the logic that's deactivated in hubble in when draining
=> fix(hubble): drain should not stop enricher

docs/astro.config.ts, docs/src/content/docs/infrastructure/node-operators/getting-started.mdx, docs/src/content/docs/infrastructure/node-operators/nixos.mdx, docs/src/content/docs/joining-testnet/upgrade-history.mdx
- Updates operator docs with current information
- Updates upgrade history of `union-testnet-10`
- Exposes `union-testnet-10` network information
=> docs: update nixos docs with more recent config op

docs/astro.config.ts, docs/src/content/docs/integrations/typescript/guided-tutorial/cosmos-call.mdx, docs/src/content/docs/integrations/typescript/guided-tutorial/cosmos-union-sepolia.mdx, docs/src/content/docs/integrations/typescript/guided-tutorial/evm-holesky-sepolia.mdx
Adds three guides to walk through creating our TS examples
=> docs: create guides for TS SDK examples
